// <auto-generated />
namespace CashJobSite.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReporterIpAddress_To_JobReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReporterIpAddress_To_JobReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201609021019172_AddReporterIpAddress_To_JobReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
